import Head from "next/head";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillFacebook } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {SiExpress,SiReact, SiNodedotjs, SiMongodb} from "react-icons/si";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import Typical from "react-typical";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const currentYear = new Date().getFullYear();

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Akash Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-300 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
{/* Section 1 starts now */}
        <div className="min-h-screen">
{/* Header/navbar */}
          <nav className="py-10 mb-8 flex justify-between text-gray-700 dark:text-white">
            <h1 className="font-burtons text-4xl ">ASB infotech</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="/Akash_Bhatiya_Resume.pdf" download="Akash_Bhatiya_Resume.pdf">
                  <button>Resume</button>
                </a>
              </li>
            </ul>
          </nav>

{/* profile */}
          <div className="lg:flex gap-20">
            <div className="text-center my-auto">
              <h2 className="text-5xl text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Akash Bhatiya</h2>
              <div className="text-2xl text-gray-700 dark:text-white md:text-3xl">
                <span>
                    {" "}
                    <h1>
                    {" "}
                    <Typical loop ={Infinity} steps={[
                      "Wordpress Developer ",
                      2000,
                      "Full Stack Developer",
                      2000,
                      "MERN Stack Developer",
                      2000,
                      "Cross Platform Dev",
                      2000,
                      "React/React Native Dev",
                      2000,
                    ]}/>
                    </h1>
                </span>
              </div>
              <p className="text-md leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                Knock of building application with front and back end operations. Join me down below and let's get cracking!
              </p>
              <div className="text-5xl flex justify-center gap-10 pb-10 pt-2 text-gray-600 dark:text-gray-400">
                <AiFillLinkedin />
                <a href="https://www.instagram.com/akash_bhatiya_00/"><AiFillInstagram /></a>
                <AiFillFacebook />
                <AiFillTwitterCircle />
              </div>
            </div>

            <div>
              <div className="mx-auto bg-gray-500 dark:bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
              </div>
            </div>
            
          </div>

        
{/* Section 2 starts now */}
          <div className="pt-20">
            <h3 className="text-4xl text-center pb-1 text-gray-800 dark:text-gray-300 "><b>Services</b></h3>
            <p className="text-md text-center py-2 leading-8 text-gray-700 dark:text-gray-400 max-w-2xl mx-auto md:text-xl">
              Since the beginning of my journey as a freelancing developer, I've done remote work for
              <span className="text-teal-600"> agencies </span>
              ,consulted for <span className="text-teal-600">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md text-center py-2 leading-8 text-gray-700 dark:text-gray-400 max-w-2xl mx-auto md:text-xl">
              I offer from a wide range of services, including brand design,
              programming and website maintence.
            </p>
          </div>
        </div>

{/* Design block card*/}
        <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-900 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg text-white dark:text-gray-900 font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2 text-white dark:text-gray-900">
                Creating elegant designs suited for your websites following core design theory.
              </p>
              <br/>
              <h4 className="py-4 text-teal-500"><b>CSS Frameworks I Use</b></h4>
              <p className="text-gray-400 dark:text-gray-900 py-1">Tailwind CSS</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Bootstrap</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Bulma</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Skeleton</p>              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-900 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} className="mx-auto"/>
              <h3 className="text-lg text-white dark:text-gray-900 font-medium pt-8 pb-2 ">
                Code your dream projects
              </h3>
              <p className="py-2 text-white dark:text-gray-900">
                Do you have an idea for your next great website? Let's make it a
                reality with single page web-application.
              </p>
              <h4 className="py-4 text-teal-500"><b>JS Frameworks I Use</b></h4>
              <p className="text-gray-400 dark:text-gray-900 py-1">React.JS</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Express.JS</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Node.JS</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">MongoDB</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-900 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg text-white dark:text-gray-900 font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2 text-white dark:text-gray-900">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-500"><b>We can meet at</b></h4>
              <p className="text-gray-400 dark:text-gray-900 py-1">Google Meet</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Whatsapp</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Facebook</p>
              <p className="text-gray-400 dark:text-gray-900 py-1">Instagram</p>
            </div>
        </div>

{/* MERN stack blocks */}
        <section>
          <h3 className="text-4xl text-center pb-1 text-gray-800 dark:text-gray-300"><b>MERN Stack</b></h3>
          <div className="lg:flex md:grid md:grid-cols-2 gap-10">
            <div className = "max-w-sm mx-auto rounded hover:-translate-y-2 overflow-hidden shadow-lg mt-10 bg-gray-500">
              <SiReact className ="mx-auto mt-5 text-4xl text-white"/>
              <div className = "px-6 py-4">
                <div className = "font-bold text-xl text-white text-center mb-2">ReactJs</div>
                <p className = "text-white text-center text-base">
                  Potent Javascript framework for building impeccable user-interfaces.
                </p>
              </div>
            </div>
            <div className = "max-w-sm mx-auto rounded hover:-translate-y-2 overflow-hidden shadow-lg mt-10 bg-gray-500">
              <SiNodedotjs className ="mx-auto mt-5 text-4xl text-white"/>
              <div className = "px-6 py-4">
                <div className = "font-bold text-xl text-white text-center mb-2">NodeJs</div>
                <p className = "text-white text-center text-base">
                  NodeJs is an open-source, cross-platform Javascript runtime environment.
                </p>
              </div>
            </div>
            <div className = "max-w-sm mx-auto rounded hover:-translate-y-2 overflow-hidden shadow-lg mt-10 bg-gray-500">
              <SiExpress className ="mx-auto mt-5 text-4xl text-white"/>
              <div className = "px-6 py-4">
                <div className = "font-bold text-xl text-white text-center mb-2">ExpressJs</div>
                <p className = "text-white text-center text-base">
                  ExpressJs or simply Express is a web application framework for NodeJs.
                </p>
              </div>
            </div>
            <div className = "max-w-sm mx-auto rounded hover:-translate-y-2 overflow-hidden shadow-lg mt-10 bg-gray-500">
              <SiMongodb className ="mx-auto mt-5 text-4xl text-white"/>
              <div className = "px-6 py-4">
                <div className = "font-bold text-xl text-white text-center mb-2">MongoDB</div>
                <p className = "text-white text-center text-base">
                  For large data transactions and for implementing a scalable model.
                </p>
              </div>
            </div>
          </div>   
        </section>


{/* Section 3 starts now */}
        <section className="pt-8">
          <div>
            <h3 className="text-4xl text-center pb-1 text-gray-800 dark:text-gray-300"><b>Sample Templetes</b></h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web1} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web2} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web3} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web5} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web4} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web6} />
            </div>
          </div>
        </section>

{/* Contact Form */}
<section className=" flex flex-col justify-center items-center">
          <div className="mt-8 text-gray-800 text-xl font-bold">
            <h1>Contact Form</h1>
          </div>
          <div className="w-full  mt-5 sm:max-w-md md:lg:max-w-xl">
            <form className="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
              <div className="mb-4">
                <label
                  className="block text-gray-700 text-sm font-bold mb-2"
                  for="username"
                >
                  Username
                </label>
                <input
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-white leading-tight focus:outline-none focus:shadow-outline"
                  id="username"
                  type="text"
                  placeholder="Enter your name"
                  required
                />
              </div>
              <div className="mb-4">
                <label
                  className="block text-gray-700 text-sm font-bold mb-2"
                  for="email"
                >
                  Email
                </label>
                <input
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-white leading-tight focus:outline-none focus:shadow-outline"
                  id="email"
                  type="text"
                  placeholder="Enter your email address"
                />
              </div>
              <div className="mb-4">
                <label
                  className="block text-gray-700 text-sm font-bold mb-2"
                  for="subject"
                >
                  Subject
                </label>
                <input
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-white leading-tight focus:outline-none focus:shadow-outline"
                  id="subject"
                  type="text"
                  placeholder="Title of your message"
                />
              </div>
              <div className="mb-4">
                <label
                  className="block text-gray-700 text-sm font-bold mb-2"
                  for="message"
                >
                  Message
                </label>
                <textarea
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-white leading-tight focus:outline-none focus:shadow-outline"
                  cols="30"
                  rows="5"
                  id="messege"
                  type="text"
                  placeholder="Enter your messege here"
                />
              </div>
              <div class="flex items-center justify-center">
                <button
                  className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                  type="button"
                >
                  Submit
                </button>
              </div>
            </form>
            <p class="text-center text-gray-500 text-xs">
              &copy; {currentYear} Akash Bhatiya. All rights reserved.
            </p>
          </div>
        </section>

{/* Footer */}
        <div className="border-t-2 mt-8 border-gray-700 dark:border-gray-300 text-gray-700 dark:text-gray-300">
          <div className="pt-10 text-center">
            <p className="">© {currentYear} <strong>Akash Bhatiya</strong></p>
          </div>
          <div className=" pt-5 pb-10 text-center">
            <p className="font-burtons text-4xl">ASB infotech</p>
          </div>
        </div>
      </main>
    </div>
  );
}


